<?php

declare(strict_types=1);

namespace Tests;

use App\Models\Map;
use App\Models\Gps;
use App\Models\PathFinder;
use PHPUnit\Framework\TestCase;

class PathFinderTest extends TestCase
{
    /**
     * @dataProvider provider
     * @param string $map
     * @param string $result
     * @return void
     */
    public function testItCanFindEndingOfAMaze(string $map, string $result): void
    {
        $map = new Map($map);

        $gps = new Gps($map);

        $pathFinder = new PathFinder(
            $gps->find('C'),
            $gps->find('R'),
            $map
        );

        $mazeStringWithPath = $pathFinder->stringWithPath;

        $this->assertEquals(
            $result,
            $mazeStringWithPath
        );
    }

    public function provider(): array
    {
        return [
            [
                    'map' => "CBBLLWLLWWWWLLBBR|"
                           . "L_BLLWLLWWWWLLBB_|"
                           . "L_BBLLWLWWWWLLBB_|"
                           . "LL_BLLWLWWWWLLBB_|"
                           . "LLL_LLWLWWWWLLBB_|"
                           . "LLLL_LWLWWWWLLBB_|"
                           . "LLLLW_LLWWWWLLBB_|"
                           . "LLLLWL_LWWWWLLB_B|"
                           . "LLLLWL_LWWWWLB_BB|"
                           . "LLLLWL_LWWWWL_BBB|"
                           . "LLLLWL_LWWWWL_BBB|"
                           . "LLLLWL___________",

                'result' => ".BBLLWLLWWWWLLBB.\n"
                          . "L.BLLWLLWWWWLLBB.\n"
                          . "L.BBLLWLWWWWLLBB.\n"
                          . "LL.BLLWLWWWWLLBB.\n"
                          . "LLL.LLWLWWWWLLBB.\n"
                          . "LLLL.LWLWWWWLLBB.\n"
                          . "LLLLW.LLWWWWLLBB.\n"
                          . "LLLLWL.LWWWWLLB.B\n"
                          . "LLLLWL.LWWWWLB.BB\n"
                          . "LLLLWL.LWWWWL.BBB\n"
                          . "LLLLWL.LWWWWL.BBB\n"
                          . "LLLLWL_......____"
            ],
            [
                    'map' => "CBBLLWLLWWWWLLBBR|"
                           . "L_BLLWLLWWWWLLBB_|"
                           . "L________________|"
                           . "LL_BLLWLWWWWLLBB_|"
                           . "LLL_LLWLWWWWLLBB_|"
                           . "LLLL_LWLWWWWLLBB_|"
                           . "LLLLW_LLWWWWLLBB_|"
                           . "LLLLWL_LWWWWLLB_B|"
                           . "LLLLWL_LWWWWLB_BB|"
                           . "LLLLWL_LWWWWL_BBB|"
                           . "LLLLWL_LWWWWL_BBB|"
                           . "LLLLWL___________",

                'result' => ".BBLLWLLWWWWLLBB.\n"
                          . "L.BLLWLLWWWWLLBB.\n"
                          . "L_.............._\n"
                          . "LL_BLLWLWWWWLLBB_\n"
                          . "LLL_LLWLWWWWLLBB_\n"
                          . "LLLL_LWLWWWWLLBB_\n"
                          . "LLLLW_LLWWWWLLBB_\n"
                          . "LLLLWL_LWWWWLLB_B\n"
                          . "LLLLWL_LWWWWLB_BB\n"
                          . "LLLLWL_LWWWWL_BBB\n"
                          . "LLLLWL_LWWWWL_BBB\n"
                          . "LLLLWL___________"
            ],
            [
                    'map' => "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW____________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWW____________________WWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW__________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "_________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_______RWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWW____________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWC_______WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                           . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",

                'result' =>   "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_.........._WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWW_......_WWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWW....................WWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_......___WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_____.__WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW______._WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "________.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_______.WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_______.WWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_.........._WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW._______WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWW......._WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
            ],
            [
                    'map' => "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW____________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWW____________________WWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW__________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "_________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_______RWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWW____________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW____________________________________WWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWC_______WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",

                'result' =>   "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW____________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWW____________________WWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW__________WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "_________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW________WWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW______..WWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWW____________WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW_.................................._WWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWW.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWW......._WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"
                            . "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
            ]
        ];
    }
}
